<a href="https://colab.research.google.com/github/MarvDaParndAndy/MAT-421-Material/blob/main/MAT_421_HW_module_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW Module D: 1.1-1.3
Jacob Camacho


*   1.1: Introduction
*   1.2: Elements of Linear Algebra 
*   1.3: Linear Regression 


# 1.1:Introduction


*  Linear algebra is a field of mathematics that is widely used in various disci-
plines. Linear algebra plays an important role in data science and machine
learning


# 1.2: Elements of Linear Algebra   

*   Definition 1.2.1(Linear Subspace): A linear subspace of V is a subset U ⊆ V
that is closed under vector addition and scalar multiplication. That is, for all
u1,u2 ∈ U and α∈ R, it holds that: u1 +u2 ∈ U,and αu1 ∈ U.
*   Definition 1.2.2(Span):Let w1,...,wm ∈ V . The span of {w1,...,wm}, denoted
span(w1,...,wm), is the set of all linear combinations of the wj ’s. That is,
span(w1,...,wm)=
{ 
∑_j=1^m αj wj : α1,...,αm ∈ R}
* Lemma 1.2.3: Ever Span is a Linear SubSpace. Let W =span(w1,...,wm).
Then W is a linear subspace.

In [2]:
import numpy as np 
x = np.array([[5, 7, 3]])
y = np.array([[2, 6, 7]])
print(np.cross(x,y))

[[ 31 -29  16]]


*   Definition 1.2.4(Column Space): Let A ∈ Rn×m be an n×m matrix with columns
a1,...,am ∈ Rn. The column space of A, denoted col(A), is the span of the
columns of A, that is, col(A)=span(a1,...,am)∈ Rn.
*   Definition 1.2.5(Linear Independence):A list of vectors u1,...,um is linearly
independent if none of them can be written as a linear combination of the
others, that is, ∀i,ui /∈ span({uj : j ̸=i}). A list of vectors is called linearly dependent if it is not linearly independent.
*   Theorem 1.2.8(Dimension Theorem): Let U be a linear subspace of V . Any
basis of U always has the same number of elements. All bases of U have the
same length, that is, the same number of elements. We call this number the
dimension of U and denote it dim(U ).

* Lemma 1.2.9(Characterization of Linearly Dependent Sets): Let u1,...,um be
a linearly dependent list of vectors with linearly independent subset, ui,i ∈
{1,...,k},k <m. Then there is an i >k such that:

1. ui ∈ span(u1,...,ui−1)
2.   span({uj : j ∈ {1,...,m}})=span({uj : j ∈ {1,...,m},j ̸=i})
* Orthonormality: A list of vectors {u1,...,um} is orthonormal if the u's are pairwise orthogonal and each has a norm of 1.
*  Best Approximation Theorem: Let U⊆ V be a linear sub-
space with orthonormal basis q1,...,qm and let v ∈ V . For any u ∈ U:    ∥v− PUv∥ ≤ ∥v− u∥.
*   Lemma 1.2.17(Pythagorean Theorem): Let u,v ∈V be orthogonal. Then ∥u+
v∥^2 =∥u∥^2 +∥v∥^2
*   Cauchy-Schwarz: For any u,v ∈ V , |⟨u,v⟩| ≤ ∥u∥∥v∥
* Gram-Schmidt: Let a1,...,am in Rn be linearly indepen-
dent. Then there exist an orthonormal basis q1,...,qm of span(a1,...,am).
* Eigenvalues and Eigenvectors: Let A ∈ R^d×d be a square
matrix. Then λ∈ Ris an eigenvalue of A if there exists a nonzero vector x ̸=0
such that: Ax =λx. The vector x is referred to as an eigenvector.

In [3]:
import numpy as np
from numpy.linalg import eig
x = np.array([[5,6],[2,8]])
w,v = eig(x)
print('E-value:', w)
print('E-vector', v)

E-value: [ 2.72508278 10.27491722]
E-vector [[-0.93504634 -0.75102896]
 [ 0.3545255  -0.66026926]]



*   Diagonal and Similar Matrices: Let A be similar to a matrix D = diag(𝜆1,...,𝜆d) with distinct diagonal entries, that exists a non-singular matric A such that A = PDP^-1
If A is symmetric, then any 2 eigen vectors from different eigenspaces are orthogonal. 
*   The Spectral Theorem of Symmetirc Matrices: A nxn symmetric matrix A has the following properties:


1. A has n eigenvalues, counting multiplicities  
2.   If 𝜆 is an eigenvalues of A with multiplicity k, then the eigenspace for x is k-dimensional.
3. The eigenspaces are mutually orthogonal, in the sense that eigenvectrs corresponding to different vaues are orthogonal.
4. A is orthogonally diagonalizable.




# 1.3: Linear Regression


*   QR Decomposition: A useful procedure to solve the linear least square problem using Gram-Schmidt.



In [4]:
import numpy as np
from numpy.linalg import qr
x = np.array([[2,5], [10,5]])

Q,R = qr(x) 
print('Q:', Q)
print('R:', R)

z = np.dot(Q, R)
print('QR', z)

iterations = [1,25]
for i in range(25): 
  Q,R = qr(x)
  x = np.dot(R, Q)
  if i+1 in iterations: 
    print(f'Iteration {i+1}:')
    print(x)

Q: [[-0.19611614 -0.98058068]
 [-0.98058068  0.19611614]]
R: [[-10.19803903  -5.88348405]
 [  0.          -3.9223227 ]]
QR [[ 2.  5.]
 [10.  5.]]
Iteration 1:
[[ 7.76923077  8.84615385]
 [ 3.84615385 -0.76923077]]
Iteration 25:
[[ 1.07284161e+01  5.00000000e+00]
 [ 5.26767774e-11 -3.72841615e+00]]




*   Normal Equations - Let A ∊ R^(nxm) be an nxm matrix with linearly independent columns and let b ∊ R^n be a vector. The solution to the least-squares problem min||Ax-b|| satisfies A^T Ax = A^T b which are known as the normal equations.
* Least Squares via QR - Let A ∊ R^(nxm) be an nxm matrix with linearly independent column, let b ∊ R^n be a vector and let A = QR be a QR decomposition of A where Q is a R^(nxm) matrix with Q^T Q = I(mxm) and T is an upper triangle.

